package com.sevak_avet.logic;

public class TopicTest {
    public static final String[] rusTopic = {
            "Этот образ, поражающий свой душевной простотой и искренностью, по-настоящему трогает сердца читателей, и не случайно великий поэт придал ему столь красочные и выразительные черты доброты, скромности и, вместе с тем, силы духа.\n" +
                    " Пушкинская Татьяна, провинциальная барышня, живущая на лоне природы, в тиши и уединении, являет собой милый и с самых первых страниц притягательный своим меланхоличным очарованием образ. И лишь с дальнейшим ходом событий мы наблюдаем в этой уравновешенной и послушной девушке жаркую бурю страстей, пылающую огнем любовь, снедающую все ее существо.\n" +
                    " Ее переживания близки и понятны каждому, кому посчастливилось полюбить в своей жизни, и проницательный читатель может в полной мере осознать ту боль, доставленную снисходительным пренебрежением героя к ее отчаянному и поражающему своей чистотой признанию.\n" +
                    " Но, несмотря на крах своих надежд и мучительные страдания, Татьяна в глубине души благодарна равнодушному герою за полноту жизни и всплеск эмоций, которые он подарил ей своим губительным появлением. И лишь подлинное величие души и сила воли могли дать ему прощение за свою первую поруганную любовь, любовь, которая, увы, не прошла, а стала тайной и постоянно кровоточащей раной, невзирая на блеск и богатство успешного брака.\n" +
                    " И этот поразительный контраст внешнего спокойствия, затаенной боли и бурлящих в душе страстей чрезвычайно любим читателем так же, как и его великим автором.",

            " Человеческая речь – великий дар природы, но это вовсе не означает, что каждому от рождения присущ и талант общения. Ведь нельзя не согласиться с тем, что одно лишь умение говорить и жестикулировать не может сделать человека прекрасным собеседником. И чтобы добиться в искусстве общения высоких успехов, необходимо обладать необычайно тонким и безошибочным чутьем, недюжинным интеллектом и хорошей интуицией.\n" +
                    " Ошибочно полагает тот, кто ставит общение в зависимость от собственного монолога и, достигая известных высот в ораторском искусстве, совершенно искренне сетует на собеседника за отсутствие должного внимания, забывая о том, что общение – это, в первую очередь, умение слушать и слышать своего визави, уделяя его словам и жестам предельно уважительное внимание.\n" +
                    " И действительно, сложно назвать хорошим собеседником того, кто старается играть ведущую и даже авторитарную роль в любом диалоге, тогда как подлинное умение общаться всегда подразумевает деликатность и компромисс.\n" +
                    " Известно также, что отнюдь не всегда основной смысл разговора лежит на поверхности и произносится вслух. По-настоящему искусный диалог – это целый комплекс слов и жестов, мимики и взглядов. Овладеть мастерством общения может лишь проницательный человек, обладающий искренним желанием собственного совершенствования.\n" +
                    " Однако это вовсе не означает, что такие навыки общения доступны лишь самым опытным и пожилым собеседникам. Безупречному диалогу можно научиться также будучи эрудированным и прилежным читателем классической литературы, авторы которой слыли не только величайшими мастерами слова, но и истинными знатоками человеческой души.",

            "  Центральный образ романа Л. Н. Толстого «Война и мир», очаровательная и прелестная Наташа Ростова, стала своеобразным символом чистоты, нежности и бесконечной доброты. В ней соединились привлекательнейшие черты искренности, веселого нрава, патриотизма и необычайного дара распространять вокруг себя дружелюбие и любовь.\n" +
                    " В начале романа мы видим в Наташе лишь трогательную в своей милой непосредственности девочку, а затем с замиранием сердца следим за ее превращением из нескладного подростка в полную соблазнительного очарования барышню, притягивающую восхищенные взоры и вызывающую волнующие чувства даже у столь твердых и многое переживших как князь Андрей.\n" +
                    " Становление этой незаурядной личности вызывает живой интерес читателя. Сквозь призму трудных для России лет мы видим взрослеющую не по годам девушку, чья душа полна любви и сострадания к ближнему, для которой дружба, честь и правда – не пустые звуки. Наташа – это образ женщины высокого происхождения, близко воспринимающей беды своей родины. И не в пример своим сверстницам, чопорной Вере или жеманной Жюли, Наташа открыта для людских страданий, она тонко чувствует и сопереживает, она необычайно тонка и деликатна, и симпатии читателя всегда на ее стороне, сколь досадными ни показались бы ее ошибки и безрассудными поступки.\n" +
                    " Наташа Ростова – бесспорное украшение романа, ее образ передан автором необычайно живо и тонко, вызывая самые добрые и трепетные чувства к ее истинной женственности, природной веселости и чистой, всеобъемлющей любви.",

            " Размышляя о законах построения литературного произведения, мы неминуемо анализируем и личность главного героя, однако далеко не всегда этот персонаж является положительным, как произошло это и в комедии великого Гоголя.\n" +
                    " И действительно, главное лицо «Ревизора» - персона аморальная. Это погрязший в карточных долгах кутила, занимающий ничтожное положение в столице, однако не лишенный известного себялюбия и тщеславия. Оказавшись в счастливых для себя обстоятельствах, будучи принятым неискушенными провинциалами за высокий чин из Петербурга, он немедленно старается обратить ситуацию в свою пользу, чего и добивается с успехом.\n" +
                    " И при всей своей порочности и никчемности, это человек помогает автору обличить целый ряд продажных и насквозь пропитанных фальшью чиновников во главе с опытным и беспринципным вором, городничим. Эта свора жалких проходимцев, проживающих свой век в удовольствиях, купленных за взятки и открыто присвоенные государственные средства, в конце комедии терпит окончательное и бесповоротное поражение, и дальнейшая их участь подразумевает полное разоблачение и серьезные взыскания.\n" +
                    " Так Хлестаков, будучи лживым и эгоистичным вертопрахом, косвенно становится бичом в руках справедливости, наказующей недостойных государственных деятелей, и позитивная роль его в данном деянии очевидна: он вместе с автором и его читателями высмеивает порочную натуру обитателей этого города, позорящих высокое звание слуг народа.",

            " Свежий и чистый воздух, кристальная вода в реках, лазурное море, густые и зеленые леса и луга – трудно перечесть все природные красоты, дарящие человеку свою целебную силу, гармонию и отдохновение. Увы, сегодня все эти бесценные блага находятся в достаточно серьезной опасности, которая долгие годы зрела и создавалась неблагодарным человечеством.\n" +
                    " Привычка к безжалостной эксплуатации природы, бездумное и алчное использование ее ресурсов могут привести к всеобъемлющей катастрофе, которая безвозвратно поглотит все лучшее, что есть на земле, оставляя жестокому и столь недальновидному человеку лишь скудность бесплодной пустыни.\n" +
                    " К счастью, сегодня многочисленные общества охраны природы с готовностью принимают на себя заботы об окружающей среде, открыто борясь с теми, кто посягает на ее девственную чистоту. В наши дни многие предприятия стараются переходить на более щадящие для природы и энергосберегающие режимы работы, что существенно снизит опасность всяческих загрязнений.\n" +
                    " Однако это вовсе не означает, что роль каждого человека в деле защиты природы пренебрежительно мала. Напротив, чистота родного края – это, в первую очередь, достижение каждого его жителя. И разводя костры или разбрасывая мусор, не стоит ожидать, что последствия данного вреда будут устранены какими-либо чудесными силами или общими усилиями крупных международных организаций. Не стоит сетовать на загазованный воздух и загрязненные зеленые рекреации, стараясь при этом самоустраниться от этих проблем. Ведь охрана природы – это дело всех и каждого в отдельности, и желаемый порядок следует, прежде всего, начинать с самого себя.\n" +
                    " И тогда материнская доброта природы вновь заключит человека в свои щедрые объятия, от души одаривая его всеми своими благами. И к этому дню мы сможем дойти лишь общими усилиями, честным трудом и чистыми, бескорыстными помыслами."
    };

    public static final String[] engTopic = {
            "My full name is Bushueva Valeria Dmitrievna. I was born in Moscow, Russia in 2002. I'm 11 years old. About my appearance, I'm tall and thin (probably), I have big blue eyes and blond hair. About my character, I am very friendly, but only with people that I think are quite good. I happen really impatient and curious, but I do not consider it a disadvantage. Do not know whether to write. I think I've told everything about myself. I do not think my life is boring because every day confronted with something new and interesting for me. For example: meeting new people at school or a meeting with the best friends. \n" +
                    "That's all! ",

            "It is winter now and it is often cold. I really can't stand the cold. So sometime ago I suddenly fell ill. I had a high temperature, a running nose and a sore throat. I also had a splitting headache and a cough. My whole body was aching. My mother fixed me a hot lemonade but that didn't help me much. She wanted to give me some aspirin too, but there wasn't any at home. My mother told me to stay in bed and called a doctor. The doctor came, took off his coat and put on his white gown. The doctor asked me to strip to the waist. He examined my lungs and throat, took my pulse and temperature, measured my blood pressure. Finally he said that it was a light case of flu and told me to stay in bed and have complete rest. He wrote a prescription for some gargle and cough medicine. He also gave me some sulfa pills, a slip for X-Ray and blood examination. He recommended to apply glass-cups and mustard plasters. I followed all the doctor's instructions and very soon I felt much better. I fully recovered in ten days and resumed my studies.",

            "Your family are probably the most important people in your life. Families consist of parents and children. But we can also say that family is a group of people consisting of a parent and children and their close relations. I think that it is better to have a big family because your relations always help and support you. \n" +
                    "I have a big family. I haven't got brothers and sisters but I have grandparents, cousins, aunts, unckles and over relations. \n" +
                    "To my mind the ideal family is then people have much in common, then they love each over, spend many time together, support and help each over. This family should be friendly. \n" +
                    "My parents and I spend many time together. At weekands we watch TV, ski, swim in the swimming pool, travel and play different games as football and voleyball. Also we spend holydays together. \n" +
                    "Thats all for now.",

            "After each term in school we had our holidays. It's fun to have holidays, you can do whatever you like, you don't have to get up too early, do your homework or think of troubles which occur very often at school. Most of all I liked summer holidays, they were the longest ones, though, when winter was snowy and and frosty, I enjoyed my winter holidays skating and skiing, sledging and making a snowman or having a fight with snowballs.\n" +
                    "I'd like to tell you about my summer holidays I spent in Sochi. It was just three years ago. My parents and me were sitting in the living-room discussing our plans for the summer holidays. My father suggested that we should go to Sochi. On hearing that I jumped up with joy and said it was a wonderful idea. My mother wasn't against the idea either.\n" +
                    "So one summer morning we started for our journey to Sochi. First, we travelled to Odessa by plane and from there we got to Sochi by boat. We stayed in Odessa for three days, our relatives live there and they gave us board and lodging. So we had an excellent opportunity to go round the city, to see beautiful monuments to the famous people who had lived in Odessa, museums and the Odessa Opera House.\n" +
                    "We enjoyed our trip from Odessa to Sochi. The Black Sea was calm. We sat on deck in the lounge chairs and looked atthe sea. I like Sochi very much. We bathed and went boating and swimming, lay in Jk the sun on the beach. In the evenings we went for a walk or dropped in at a cafe to have ice-cream or juice. My father showed us the famous Botanical Gardens, we went for hikes in the mountains, we saw the magnificent Augura Waterfalls.",

            "There are 4 of us in our family: my mother, father, my elder brother and me. I think our family is friendly and united. We spend much time together, hike, visit theaters, museums, go to the cinema. My mother's name is Luidmila Mikhailovna. She is an engineer, she works in an office. She is a kind, nice woman. She can cook very well. She is fond of reading. My father's name is Konstantin Alexeevich. He is a sailor. He is a strong, clever man. He often tells me interesting stories about different countries. Father can do a lot of things. He teaches me to repair furniture, to drive a car. My brother's name is Alexei. He is 22 years old. He has been studying in Far- Eastern State Marine Academy for 5 years. Now it is a very difficult period for him: he is taking state exams.\n" +
                    "I have my duties about the house. I must go shopping, clean the rooms. It's not difficult for me. I like our home to be clean and tidy. I think home is the nicest place. As proverb says, \"East or West, home is best\". There is no place more delightful than home and there are no people more dear than your relatives."
    };
}
